[package]
name = "loom_anvil"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
loom = { workspace = true, features = ["full-json-rpc", "strategy-full"] }

clap.workspace = true
eyre.workspace = true
futures.workspace = true
influxdb.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wiremock.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-node-bindings.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-transport-http.workspace = true
alloy-transport-ipc.workspace = true
alloy-transport-ws.workspace = true

revm.workspace = true

[dev-dependencies]
chrono.workspace = true
criterion = { version = "0.5.1", features = ["async_tokio"] }
futures.workspace = true
num_cpus.workspace = true
rand.workspace = true
rayon.workspace = true

[[bench]]
harness = false
name = "benchmark"
