[package]
name = "loom-node-exex"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
loom-core-actors.workspace = true
loom-core-blockchain.workspace = true
loom-evm-utils.workspace = true
loom-node-actor-config.workspace = true
loom-types-blockchain.workspace = true
loom-types-events.workspace = true

eyre.workspace = true
futures.workspace = true
revm.workspace = true
tokio.workspace = true
tracing.workspace = true

# alloy
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true

#reth
reth-exex.workspace = true
reth-node-api.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-rpc.workspace = true
reth-rpc-types-compat.workspace = true
reth-transaction-pool.workspace = true
