[package]
name = "loom-rpc-handler"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
loom-core-actors.workspace = true
loom-core-actors-macros.workspace = true
loom-core-blockchain.workspace = true
loom-evm-db.workspace = true
loom-evm-utils.workspace = true
loom-rpc-state.workspace = true
loom-storage-db.workspace = true
loom-types-blockchain.workspace = true
loom-types-entities.workspace = true

hex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

alloy-primitives.workspace = true
revm.workspace = true

# async
tokio.workspace = true
tokio-util.workspace = true

# tracing + error handling
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# web
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
