[package]
name = "replayer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
clap.workspace = true
env_logger.workspace = true
eyre.workspace = true
futures.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

debug-provider.workspace = true

defi-actors.workspace = true
defi-address-book.workspace = true
defi-blockchain.workspace = true
defi-blockchain-actors.workspace = true
defi-entities.workspace = true
defi-events.workspace = true
defi-pools.workspace = true
defi-types.workspace = true
loom-actors.workspace = true
loom-actors-macros.workspace = true
loom-utils.workspace = true


loom-multicaller.workspace = true

alloy.workspace = true
url = "2.5.2"
