[package]
name = "gasbench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
env_logger.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-transport.workspace = true
revm.workspace = true

loom-core-actors.workspace = true
loom-defi-address-book.workspace = true
loom-defi-market.workspace = true
loom-defi-pools.workspace = true
loom-defi-preloader.workspace = true
loom-evm-db.workspace = true
loom-evm-utils.workspace = true
loom-execution-multicaller.workspace = true
loom-node-debug-provider.workspace = true
loom-types-entities.workspace = true
