[package]
name = "loom-evm-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
loom-defi-abi.workspace = true
loom-defi-address-book.workspace = true
loom-evm-db.workspace = true
loom-node-debug-provider.workspace = true
loom-types-blockchain.workspace = true

# misc
axum.workspace = true
eyre.workspace = true
lazy_static.workspace = true
thiserror.workspace = true
tracing.workspace = true

# revm
revm.workspace = true
revm-inspectors.workspace = true

# alloy
alloy.workspace = true

# reth
reth-db.workspace = true
reth-primitives.workspace = true
reth-rpc.workspace = true
reth-rpc-types-compat.workspace = true
