[package]
name = "loom_backrun"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loom = { workspace = true, features = ["full-json-rpc", "strategy-full"] }

env_logger.workspace = true
eyre.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true

alloy.workspace = true
alloy-primitives.workspace = true
