[package]
name = "loom-protocol-pools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
loom-defi-entities.workspace = true
loom-defi-types.workspace = true
loom-evm-db.workspace = true
loom-evm-utils.workspace = true
loom-protocol-abi.workspace = true
loom-protocol-address-book.workspace = true
loom-protocol-uniswap-v3-math.workspace = true

eyre.workspace = true
lazy_static.workspace = true
reth-storage-api.workspace = true
revm.workspace = true
strum.workspace = true
tracing.workspace = true


# alloy
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-sol-macro.workspace = true
alloy-sol-types.workspace = true
alloy-transport.workspace = true

[features]
debug-calculation = []


[dev-dependencies]
loom-node-debug-provider.workspace = true

alloy-rpc-client.workspace = true
alloy-transport.workspace = true
env_logger.workspace = true
rand.workspace = true
tokio.workspace = true
url.workspace = true
